/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as BacGraphRouteImport } from './routes/bac-graph'
import { Route as AddDrinkRouteImport } from './routes/add-drink'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GroupsIndexRouteImport } from './routes/groups.index'
import { Route as DrinkPresetsIndexRouteImport } from './routes/drink-presets.index'
import { Route as GroupsJoinRouteImport } from './routes/groups.join'
import { Route as GroupsCreateRouteImport } from './routes/groups.create'
import { Route as GroupsGroupIdRouteImport } from './routes/groups.$groupId'
import { Route as EditDrinkDrinkIdRouteImport } from './routes/edit-drink.$drinkId'
import { Route as DrinkPresetsNewRouteImport } from './routes/drink-presets.new'
import { Route as DrinkPresetsPresetIdRouteImport } from './routes/drink-presets.$presetId'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const BacGraphRoute = BacGraphRouteImport.update({
  id: '/bac-graph',
  path: '/bac-graph',
  getParentRoute: () => rootRouteImport,
} as any)
const AddDrinkRoute = AddDrinkRouteImport.update({
  id: '/add-drink',
  path: '/add-drink',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const DrinkPresetsIndexRoute = DrinkPresetsIndexRouteImport.update({
  id: '/drink-presets/',
  path: '/drink-presets/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsJoinRoute = GroupsJoinRouteImport.update({
  id: '/groups/join',
  path: '/groups/join',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsCreateRoute = GroupsCreateRouteImport.update({
  id: '/groups/create',
  path: '/groups/create',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdRoute = GroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const EditDrinkDrinkIdRoute = EditDrinkDrinkIdRouteImport.update({
  id: '/edit-drink/$drinkId',
  path: '/edit-drink/$drinkId',
  getParentRoute: () => rootRouteImport,
} as any)
const DrinkPresetsNewRoute = DrinkPresetsNewRouteImport.update({
  id: '/drink-presets/new',
  path: '/drink-presets/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DrinkPresetsPresetIdRoute = DrinkPresetsPresetIdRouteImport.update({
  id: '/drink-presets/$presetId',
  path: '/drink-presets/$presetId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-drink': typeof AddDrinkRoute
  '/bac-graph': typeof BacGraphRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/drink-presets/$presetId': typeof DrinkPresetsPresetIdRoute
  '/drink-presets/new': typeof DrinkPresetsNewRoute
  '/edit-drink/$drinkId': typeof EditDrinkDrinkIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/groups/create': typeof GroupsCreateRoute
  '/groups/join': typeof GroupsJoinRoute
  '/drink-presets/': typeof DrinkPresetsIndexRoute
  '/groups/': typeof GroupsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-drink': typeof AddDrinkRoute
  '/bac-graph': typeof BacGraphRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/drink-presets/$presetId': typeof DrinkPresetsPresetIdRoute
  '/drink-presets/new': typeof DrinkPresetsNewRoute
  '/edit-drink/$drinkId': typeof EditDrinkDrinkIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/groups/create': typeof GroupsCreateRoute
  '/groups/join': typeof GroupsJoinRoute
  '/drink-presets': typeof DrinkPresetsIndexRoute
  '/groups': typeof GroupsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-drink': typeof AddDrinkRoute
  '/bac-graph': typeof BacGraphRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/drink-presets/$presetId': typeof DrinkPresetsPresetIdRoute
  '/drink-presets/new': typeof DrinkPresetsNewRoute
  '/edit-drink/$drinkId': typeof EditDrinkDrinkIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/groups/create': typeof GroupsCreateRoute
  '/groups/join': typeof GroupsJoinRoute
  '/drink-presets/': typeof DrinkPresetsIndexRoute
  '/groups/': typeof GroupsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-drink'
    | '/bac-graph'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/drink-presets/$presetId'
    | '/drink-presets/new'
    | '/edit-drink/$drinkId'
    | '/groups/$groupId'
    | '/groups/create'
    | '/groups/join'
    | '/drink-presets/'
    | '/groups/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-drink'
    | '/bac-graph'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/drink-presets/$presetId'
    | '/drink-presets/new'
    | '/edit-drink/$drinkId'
    | '/groups/$groupId'
    | '/groups/create'
    | '/groups/join'
    | '/drink-presets'
    | '/groups'
  id:
    | '__root__'
    | '/'
    | '/add-drink'
    | '/bac-graph'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/drink-presets/$presetId'
    | '/drink-presets/new'
    | '/edit-drink/$drinkId'
    | '/groups/$groupId'
    | '/groups/create'
    | '/groups/join'
    | '/drink-presets/'
    | '/groups/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddDrinkRoute: typeof AddDrinkRoute
  BacGraphRoute: typeof BacGraphRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  DrinkPresetsPresetIdRoute: typeof DrinkPresetsPresetIdRoute
  DrinkPresetsNewRoute: typeof DrinkPresetsNewRoute
  EditDrinkDrinkIdRoute: typeof EditDrinkDrinkIdRoute
  GroupsGroupIdRoute: typeof GroupsGroupIdRoute
  GroupsCreateRoute: typeof GroupsCreateRoute
  GroupsJoinRoute: typeof GroupsJoinRoute
  DrinkPresetsIndexRoute: typeof DrinkPresetsIndexRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bac-graph': {
      id: '/bac-graph'
      path: '/bac-graph'
      fullPath: '/bac-graph'
      preLoaderRoute: typeof BacGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-drink': {
      id: '/add-drink'
      path: '/add-drink'
      fullPath: '/add-drink'
      preLoaderRoute: typeof AddDrinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drink-presets/': {
      id: '/drink-presets/'
      path: '/drink-presets'
      fullPath: '/drink-presets/'
      preLoaderRoute: typeof DrinkPresetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/join': {
      id: '/groups/join'
      path: '/groups/join'
      fullPath: '/groups/join'
      preLoaderRoute: typeof GroupsJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/create': {
      id: '/groups/create'
      path: '/groups/create'
      fullPath: '/groups/create'
      preLoaderRoute: typeof GroupsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId': {
      id: '/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-drink/$drinkId': {
      id: '/edit-drink/$drinkId'
      path: '/edit-drink/$drinkId'
      fullPath: '/edit-drink/$drinkId'
      preLoaderRoute: typeof EditDrinkDrinkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drink-presets/new': {
      id: '/drink-presets/new'
      path: '/drink-presets/new'
      fullPath: '/drink-presets/new'
      preLoaderRoute: typeof DrinkPresetsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drink-presets/$presetId': {
      id: '/drink-presets/$presetId'
      path: '/drink-presets/$presetId'
      fullPath: '/drink-presets/$presetId'
      preLoaderRoute: typeof DrinkPresetsPresetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddDrinkRoute: AddDrinkRoute,
  BacGraphRoute: BacGraphRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  DrinkPresetsPresetIdRoute: DrinkPresetsPresetIdRoute,
  DrinkPresetsNewRoute: DrinkPresetsNewRoute,
  EditDrinkDrinkIdRoute: EditDrinkDrinkIdRoute,
  GroupsGroupIdRoute: GroupsGroupIdRoute,
  GroupsCreateRoute: GroupsCreateRoute,
  GroupsJoinRoute: GroupsJoinRoute,
  DrinkPresetsIndexRoute: DrinkPresetsIndexRoute,
  GroupsIndexRoute: GroupsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
